import { describe, it, expect, vi, beforeEach } from "vitest";
import request from "supertest";
import express from "express";
import { errorHandler } from "../../middleware/error-handler";
import aiRoutes from "./ai.routes";

const { mockPrisma, mockAiCron } = vi.hoisted(() => ({
  mockPrisma: {
    module: { findMany: vi.fn(), findUnique: vi.fn(), create: vi.fn(), groupBy: vi.fn() },
    cronJob: { findUnique: vi.fn(), upsert: vi.fn() },
    $disconnect: vi.fn(),
  },
  mockAiCron: { getSchedule: vi.fn(), start: vi.fn(), stop: vi.fn(), triggerOnce: vi.fn() },
}));

vi.mock("../../lib/prisma", () => ({ prisma: mockPrisma }));
vi.mock("../../lib/cache", () => ({
  Cache: { get: vi.fn().mockResolvedValue(null), set: vi.fn(), del: vi.fn(), delByPattern: vi.fn(), key: vi.fn(), PREFIXES: {} },
}));
vi.mock("../../config/env", () => ({
  env: {
    gemini: { apiKey: "test-ai-key" },
    cookie: { secure: false, domain: undefined },
    adminEmail: null,
    redis: { url: "" },
  },
}));

vi.mock("./ai.cron", () => ({ AiCron: mockAiCron }));

vi.mock("../../middleware/auth", () => ({
  authenticate: (req: any, _res: any, next: any) => {
    req.user = { userId: "admin-1", email: "admin@test.com", role: "ADMIN" };
    next();
  },
  authorize: (..._roles: string[]) => (_req: any, _res: any, next: any) => next(),
  optionalAuth: (req: any, _res: any, next: any) => {
    req.user = { userId: "admin-1", email: "admin@test.com", role: "ADMIN" };
    next();
  },
}));

const mockFetch = vi.fn();
global.fetch = mockFetch;

function createApp() {
  const app = express();
  app.use(express.json());
  app.use("/api/ai", aiRoutes);
  app.use((_req, res) => res.status(404).json({ error: { message: "Not found", statusCode: 404 } }));
  app.use(errorHandler);
  return app;
}

function fakeCategoryInfo() {
  return {
    categories: [{ name: "Mindset", count: 3 }, { name: "Focus", count: 1 }],
    existingTitles: [
      { title: "Growth Mindset", slug: "growth-mindset", category: "Mindset" },
      { title: "Deep Focus", slug: "deep-focus", category: "Focus" },
    ],
  };
}

function fakeModule(overrides: Record<string, any> = {}) {
  return {
    id: "mod-1",
    slug: "ai-module",
    title: "AI Generated Module",
    description: "Generated by AI",
    category: "Mindset",
    isPremium: true,
    isDraft: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  };
}

beforeEach(() => {
  vi.resetAllMocks();
  mockFetch.mockReset();
});

describe("AI API", () => {
  describe("GET /api/ai/categories", () => {
    it("should return categories info", async () => {
      mockPrisma.module.groupBy.mockResolvedValue([
        { category: "Mindset", _count: { category: 3 } },
      ]);
      mockPrisma.module.findMany.mockResolvedValue([
        { title: "Growth Mindset", slug: "growth-mindset", category: "Mindset", createdAt: new Date() },
      ]);
      const res = await request(createApp()).get("/api/ai/categories");
      expect(res.status).toBe(200);
      expect(res.body.categories).toHaveLength(1);
      expect(res.body.existingTitles).toHaveLength(1);
    });
  });

  describe("POST /api/ai/generate", () => {
    it("should generate questions", async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          candidates: [{ content: { parts: [{ text: '```json\n[{"question":"Q","options":["A","B"],"correctAnswer":0,"explanation":"E"}]\n```' }] } }],
        }),
      });
      const res = await request(createApp())
        .post("/api/ai/generate")
        .send({ mode: "questions", content: "Some content" });
      expect(res.status).toBe(200);
      expect(res.body.questions).toHaveLength(1);
    });

    it("should generate graph", async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          candidates: [{ content: { parts: [{ text: '```json\n{"nodes":[{"id":"n1","label":"Node 1","content":["text"]}],"edges":[{"source":"n1","target":"n2"}]}\n```' }] } }],
        }),
      });
      const res = await request(createApp())
        .post("/api/ai/generate")
        .send({ mode: "graph", content: "Some content" });
      expect(res.status).toBe(200);
      expect(res.body.nodes).toHaveLength(1);
    });

    it("should reject invalid mode", async () => {
      const res = await request(createApp())
        .post("/api/ai/generate")
        .send({ mode: "invalid" });
      expect(res.status).toBe(400);
    });

    it("should handle AI API error", async () => {
      mockFetch.mockResolvedValue({ ok: false, status: 400, text: () => Promise.resolve('{"error":{"message":"Bad request"}}') });
      const res = await request(createApp())
        .post("/api/ai/generate")
        .send({ mode: "questions", content: "Content" });
      expect(res.status).toBe(502);
    });
  });

  describe("POST /api/ai/auto-generate", () => {
    it("should auto-generate module", async () => {
      mockAiCron.triggerOnce.mockResolvedValue(fakeModule());
      const res = await request(createApp()).post("/api/ai/auto-generate").send({ category: "Mindset" });
      expect(res.status).toBe(201);
    });

    it("should handle invalid AI response", async () => {
      const { AppError } = await import("../../lib/errors");
      mockAiCron.triggerOnce.mockRejectedValue(new AppError("Invalid AI response", 502));
      const res = await request(createApp()).post("/api/ai/auto-generate");
      expect(res.status).toBe(502);
    });
  });

  describe("GET /api/ai/schedule", () => {
    it("should return schedule", async () => {
      mockAiCron.getSchedule.mockResolvedValue({
        expression: "0 0 * * *",
        category: "Mindset",
        createdAt: new Date().toISOString(),
        isActive: true,
      });
      const res = await request(createApp()).get("/api/ai/schedule");
      expect(res.status).toBe(200);
      expect(res.body.isActive).toBe(true);
    });

    it("should return inactive when no schedule", async () => {
      mockAiCron.getSchedule.mockResolvedValue(null);
      const res = await request(createApp()).get("/api/ai/schedule");
      expect(res.status).toBe(200);
      expect(res.body.isActive).toBe(false);
    });
  });

  describe("POST /api/ai/schedule", () => {
    it("should set schedule", async () => {
      mockPrisma.cronJob.upsert.mockResolvedValue({});
      const res = await request(createApp())
        .post("/api/ai/schedule")
        .send({ expression: "0 0 * * *", category: "Mindset" });
      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
    });

    it("should reject invalid cron expression", async () => {
      const res = await request(createApp())
        .post("/api/ai/schedule")
        .send({ expression: "invalid" });
      expect(res.status).toBe(400);
    });
  });

  describe("DELETE /api/ai/schedule", () => {
    it("should delete schedule", async () => {
      mockPrisma.cronJob.upsert.mockResolvedValue({});
      const res = await request(createApp()).delete("/api/ai/schedule");
      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
    });
  });
});
